### ISSUE TITLE
Running aa-sdk in AWS lambda to fire user operations

### ISSUE THREAD

**Issue by yashh** [alchemyplatform/aa-sdk#15]
### [REQUIRED] Environment

- Browser version:
- AA SDK version:
- Package:

#### Relevant code or sample repro:

```
import { Context, APIGatewayProxyResult, APIGatewayEvent } from 'aws-lambda';
import {
    alchemyPaymasterAndDataMiddleware,
    SimpleSmartContractAccount,
    SmartAccountProvider,
    type SimpleSmartAccountOwner,
} from "@alchemy/aa-core";
import { mnemonicToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";
import { toHex } from "viem";
import fetch from "node-fetch";
global.fetch = fetch;


const SIMPLE_ACCOUNT_FACTORY_ADDRESS =
    "0x9c7938fCaaDd7Ad94F6B5b4A2fd4efb8219Exxxx";
const MNEMONIC = process.env.MNEMONIC
const ENDPOINT = "https://eth-sepolia.g.alchemy.com/v2/xxxxxx"
const CHAINID = sepolia
const ENTRYPOINT = "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2790"
const PAYMASTER_POLICY_ID = "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"


// 1. define the EOA owner of the Smart Account
// This is just one exapmle of how to interact with EOAs, feel free to use any other interface
const ownerAccount = mnemonicToAccount(MNEMONIC);
// All that is important for defining an owner is that it provides a `signMessage` and `getAddress` function
const owner: SimpleSmartAccountOwner = {
    // this should sign a message according to ERC-191
    signMessage: async (msg) =>
        ownerAccount.signMessage({
            message: toHex(msg),
        }),
    getAddress: async () => ownerAccount.address,
};

// 2. initialize the provider and connect it to the account
let provider = new SmartAccountProvider(
    ENDPOINT, // rpcUrl
    ENTRYPOINT, // entryPointAddress
    CHAINID // chain
).connect(
    (rpcClient) =>
        new SimpleSmartContractAccount({
            entryPointAddress: ENTRYPOINT,
            chain: CHAINID,
            factoryAddress: SIMPLE_ACCOUNT_FACTORY_ADDRESS,
            rpcClient,
            owner,
            // optionally if you already know the account's address
            // accountAddress: "0x4a994E56d791EDcf0dDADD87eF82928a5E15e591",
        })
);
provider = provider.withPaymasterMiddleware(
    alchemyPaymasterAndDataMiddleware({
        provider: provider.rpcClient,
        policyId: PAYMASTER_POLICY_ID, // <- your policy id in the screenshot
        entryPoint: ENTRYPOINT,
    })
);

export const handler = async (
    event: APIGatewayEvent,
    context: Context
): Promise<APIGatewayProxyResult> => {
    console.log(event);
    // const from_address = event["from_address"];
    const to_address = event["to_address"];
    // const data = event["data"];
    const ownerAddress = await owner.getAddress();
    console.log(`Event: ${JSON.stringify(event, null, 2)}`);
    console.log(`owner: ${ownerAddress}`);
    console.log(`AA account: ${await provider.getAddress()}`);
    console.log(`to: ${to_address}`);
    // 3. send a UserOperation
    const { hash } = await provider.sendUserOperation(
        to_address, // to = "0x20f8f072d28267d86b06743552bdaab9a0ff25d3",
        "0x",
        0n // value: bigint or undefined
    );
    return {
        statusCode: 200,
        body: JSON.stringify({
            message: 'Running this handler from docker',
            hash: hash
        }),
    };
};```


```
{"errorType":"InvalidAddressError","errorMessage":"Address \"undefined\" is invalid.\n\nVersion: viem@0.3.17","shortMessage":"Address \"undefined\" is invalid.","name":"InvalidAddressError","version":"viem@0.3.17","message":"Address \"undefined\" is invalid.\n\nVersion: viem@0.3.17","stack":["InvalidAddressError: Address \"undefined\" is invalid.","","Version: viem@0.3.17","    at YP (/var/task/index.js:27:17710)","    at Xm (/var/task/index.js:27:17119)","    at ZP (/var/task/index.js:27:16900)","    at ot (/var/task/index.js:27:16765)","    at we (/var/task/index.js:27:26154)","    at il.encodeExecute (/var/task/index.js:18479:67558)","    at cl.value [as sendUserOperation] (/var/task/index.js:18479:72513)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async Runtime.V_ [as handler] (/var/task/index.js:18482:1328)"]}
END RequestId: 197b7f81-1315-4c70-85db-cbf1f550873d
REPORT RequestId: 197b7f81-1315-4c70-85db-cbf1f550873d	Duration: 1677.03 ms	Billed Duration: 2525 ms	Memory Size: 128 MB	Max Memory Used: 91 MB	Init Duration: 847.70 ms	
```

**Comment by moldy530** [comment]
`const SIMPLE_ACCOUNT_FACTORY_ADDRESS = "0x9c7938fCaaDd7Ad94F6B5b4A2fd4efb8219Exxxx";`

@yashh , just to sanity check, does you account factory actually have these 4 x's at the end? I'm assuming no, but have to check since this address can be public so no need to obfuscate here.
