### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by phDooY** [alchemyplatform/aa-sdk#725]
### [REQUIRED] Environment

- Browser version: not in browser
- AA SDK version: 3.18.2
- Package: aa-alchemy

### [REQUIRED] Describe the problem
Before and including version 3.9.0 didn't have this issue. Trying to upgrade for several weeks already, resulting in following issue:
```
: Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/@wagmi/core/dist/esm/exports/index.js from /node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js not supported.
: Instead change the require of index.js in /node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js to a dynamic import() which is available in all CommonJS modules.
:     at Hook.Module.require (/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
:     at Object.<anonymous> (/node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js:7:16) {
:   code: 'ERR_REQUIRE_ESM'
: }
: 
: Node.js v21.7.1
```

#### How to reproduce:
```
"compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2022",
    "sourceMap": true,
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "allowJs": true,
    "paths": {},
    "baseUrl": "./"
  }
  ```

**Comment by neerajnerlekar** [comment]
I am getting this same error too. Could you let me know if you were able to resolve this?

**Comment by moldy530** [comment]
@neerajnerlekar are you still seeing this on the latest version? It should have been fixed. If not can you send me an updated stacktrace?

The one in the report here seems to be related to something we fixed, so there might be something else that's not CJS compatible

**Comment by HarukiKondo** [comment]
I am getting this same error too.

**Comment by moldy530** [comment]
@HarukiKondo can you post a stack trace of your error?

**Comment by HarukiKondo** [comment]
@moldy530  Ok. Here is a stack trace in my case

```bash
node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/@wagmi/core/dist/esm/exports/index.js from node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js not supported.
Instead change the require of index.js in node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js:7:16)
    at require.extensions.<computed> [as .js] (node_modules/ts-node/dist/index.js:851:20) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/ubuntu/.nvm/versions/node/v20.13.1/bin/node
Arguments: /home/ubuntu/.nvm/versions/node/v20.13.1/lib/node_modules/yarn/lib/cli.js aa:test
Directory: /home/ubuntu/environment/NFTSmartKeyPoc/packages/cdk-nft-sample
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by HarukiKondo** [comment]
I executed on AWS Cloud9.

```json
"dependencies": {
    "@alchemy/aa-accounts": "^3.18.2",
    "@alchemy/aa-alchemy": "3.16.0",
    "@alchemy/aa-core": "3.16.0",
}
```

**Comment by moldy530** [comment]
Ah yeah, try upgrading all the packages to 3.18.2 and see if that resolves it

**Comment by HarukiKondo** [comment]
@moldy530 Thank you! I will try it!

**Comment by HarukiKondo** [comment]
@moldy530  I upgraded all the packages to 3.18.2. But I am getting this same error too.

**Comment by neerajnerlekar** [comment]
I updated it to 3.18.2 and I am still getting the same error in stack trace.

I even cloned Dan's github repo associated with the video, and it still gives the same error

Here is my `package.json`

```json
{
  "name": "aa-sdk-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.12.3",
    "ts-node": "^10.9.2",
    "typescript": "^5.4.3"
  },
  "dependencies": {
    "@alchemy/aa-alchemy": "^3.18.2",
    "@alchemy/aa-core": "^3.18.2",
    "dotenv": "^16.4.5",
    "viem": "^2.9.15"
  }
}
```

Here is the stack trace of the error.

```bash
node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/aa-sdk-userops/node_modules/@wagmi/core/dist/esm/exports/index.js from /home/aa-sdk-userops/node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js not supported.
Instead change the require of index.js in /home/aa-sdk-userops/node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/home/aa-sdk-userops/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/aa-sdk-userops/node_modules/@alchemy/aa-alchemy/dist/cjs/config/utils/cookies.js:7:16)
    at require.extensions.<computed> [as .js] (/home/aa-sdk-userops/node_modules/ts-node/dist/index.js:851:20) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by moldy530** [comment]
ah the issue is the version of wagmi :/ https://wagmi.sh/react/guides/migrate-from-v1-to-v2#dropped-commonjs-support

wagmi in v2 no longer supports CJS. Most likely you'll have to migrate over to using ESM instead of CJS. We'll take a look at the example repo as well and double check that it's setup for ESM
